### ISSUE TITLE
Nah man, I got this handled

### ISSUE THREAD

**Issue by ghost** [JonnyD/Skynet#1]
Just thought you might to know I've already made something like this so you don't need to rewrite from scratch, http://github.com/fwhiffahder/glados

I've implemented most of nickelpro's skynet functionality and just need to mirror his API. Pull requests welcome, I guess.

**Comment by ghost** [comment]
[Here are nickelpro's docs](http://www.reddit.com/r/Civcraft/comments/1vo3xx/a_suggestion_for_all_those_who_use_bots/cevb2tz?context=4)

**Comment by JonnyD** [comment]
Very nice
